version: '3.8'

services:
  mail-service:
    image: sinteligentesw/email-php:V1.0.12
    volumes:
      - .:/var/www/html
    ports:
      - "3110:80"
    env_file:
      - .env
    environment:
      - APP_ENV=local
